### ISSUE TITLE
Configurable escaping for non-HTML templates

### ISSUE THREAD

**Issue by hiltonc** [korlibs/korte#15]
I'm using Korte for a non-HTML template. The template engine is escaping values with `htmlspecialchars`. I can work around it with `RawString`, but it'd be nice if I could turn off the escaping globally, or provide an alternative or custom escaping mechanism.

**Comment by soywiz** [comment]
I don't remember right now the details, but might be already a mechanism there to do that. If not, I will add it 👍

**Comment by hiltonc** [comment]
It looks like there is a mechanism, this worked for me:

```
Templates(FileTemplateProvider(basePath), config = TemplateConfig().apply {
    writeBlockExpressionResult = { value ->
        this.write(when (value) {
            is String -> contentTypeProcessor(value, null)
            else -> contentTypeProcessor(Dynamic2.toString(value), null)
        })
    }
})
```

Awesome library btw, thank you!

**Comment by hiltonc** [comment]
Yes, that would work really well. I like how simple it is, with an obvious extension mechanism.
