### ISSUE TITLE
Crash in Kotlin native when used from a different thread

### ISSUE THREAD

**Issue by eliekarouz** [korlibs/korte#16]
Found a kotlin native problem [here](https://github.com/korlibs/korte/blob/d9e31c218a0de7d57414c79e9edb4e57f05f5230/korte/src/commonMain/kotlin/com/soywiz/korte/dynamic/ObjectMapper2.kt#L30):

```kotlin
expect val Mapper2: ObjectMapper2
```
should be marked with `@SharedImmutable` or `@ThreadLocal` otherwise, we cannot use korte from a background thread.

**Comment by soywiz** [comment]
Have you validated that? That class doesn't seem to have properties with backing fields at a first glance. If it doesn't have state that can mutate in theory, that code should be correct

**Comment by eliekarouz** [comment]
@soywiz 

You can check the details [here](https://kotlinlang.org/docs/mobile/concurrency-overview.html#global-properties).

You are right, it is a bit weird... In Kotlin native, immutability != frozen. The objects cannot cross threads even if they are immutable.

I tried to fix it and submit a pull request but the IDE is not working it is telling me that I should update to Android Studio 4.2.

**Comment by soywiz** [comment]
You should use IntelliJ instead of Android Studio. Could you provide the PR with a test showing that behavior failing in a separate test, so we can avoid future regressions?
