### ISSUE TITLE
Extention for toDynamicLocalDate()

### ISSUE THREAD

**Issue by SoftMachina** [korlibs/korte#20]
As of right now, it appears there is no way to convert the `subject` in the `Ctx` to a `LocalDate` to make comparisons in Kotlin.

**Comment by soywiz** [comment]
Hey @SoftMachina I guess I need more context to understand this. Can you put a sample of Kotlin code and template code showing what you would to do?

**Comment by MartinX3** [comment]
Hey @soywiz 
We want to render a table.
The datasource contains a startdate (localdate) and a duration in days (integer).
On this table we want to filter/remove every entry in the past or in the future.

As example
-  future entry: if the enddate (startdate + duration days) is in the past.
-  past entry: if the startdate is in the future.

Or that we can order the entries with the locadate + duration integer entries.

**Comment by soywiz** [comment]
@MartinX3 @SoftMachina Doesn't this work for you? https://github.com/korlibs/korge-next/commit/25d4520f3636657e12c1639aea03b9c7cd3eb716#diff-b77af0d60bc9f76c64298027e1d9b87e6c9ce56512f955c601c6a30f9d80058bR37
It seems to work properly already

**Comment by MartinX3** [comment]
@soywiz Thank you for your example
In our case the enduser just writes an email template in our frontend.
Is it possible to assign the individual variable names for startdate and duration in the template text or do we need to rename the database variable names to standard ones?

**Comment by soywiz** [comment]
Inside the template, you can use the set tag to create aliases, or set local variables for complex expressions:
https://docs.korge.org/korte/tags/#set

Also you can precompute endDate in kotlin code and pass it to the template.
If you need specific property names for your DTOs my suggestion is to create a separate layer of DTOs and transform your input to those DTOs so you only expose what you want and with the naming you want. Note that Kotlin extension members are not available in korte templates.

**Comment by SoftMachina** [comment]
@soywiz my question may has been a little to vague, I'm sorry for that. What I'm trying to do is, writing a custom filter to filter out dates in a table that are < today. For that, I use something like `[startingDate, duration] | onlyFuture` in the template. In the Kotlin backend, I then proceed to use the `subject` in the context of the filter, to get my hands on both these values. My initial issue was that I have to convert the `startingDate` from String to LocalDate myself, which I would much rather prefer to be an extension of the `Dynamic2` thing you wrote. That way, the hassle of conversion could be avoided.

**Comment by soywiz** [comment]
@SoftMachina `Dynamic2` is in the Kotlin/Common sourceSet. Kotlin Common doesn't have dates yet in the standard library, so it would be a bit problematic handling dates there because of that
