### ISSUE TITLE
Accessing a property in a list of object not working on IOS

### ISSUE THREAD

**Issue by RZahr** [korlibs/korte#24]
Example case:

`@Serializable
    data class Output(val value: String, val index: Int) : DynamicType<Output> by DynamicType({`
        `register(Output::value)`
       ` register(Output::index)`
   ` })`

`val values = listOf(Output("Yes", 0))`

`val template = Template("{{values[0].value}}", TemplateConfig())`
`return template(this) //works on android. On IOS i am receiving a segmentation crash`

**Comment by soywiz** [comment]
Duplicate of https://github.com/korlibs/korte/issues/25
