### ISSUE TITLE
Decoding from string to serialized data class and accessing its properties on IOS causing segmentation fault

### ISSUE THREAD

**Issue by RZahr** [korlibs/korte#25]
fun testUser(): User? {
        val x = """{
                    "key": "test user",
                    "firstName": "test",
                    "lastName": "test"
                }"""

        return Json.decodeFromString(User.serializer(), x)
    }

@Serializable
data class User(val key: String, val firstName: String, val lastName: String) :
    DynamicType<User> by DynamicType({
        register(User::key)
        register(User::firstName)
        register(User::lastName)
    })

i am exposing this function to use it in a expression where the user also has its properties exposed

evaluating testUser().key is working when testing on android but on IOS i am receiving a segmentation fault

**Comment by soywiz** [comment]
Unfortunately it seems that when deserializing using kotlinx.serialization a class with `DynamicType by DynamicType({})` the object is not fully working, and there is a null pointer exception trying to access the internal machinery of the DynamicType.

A proposed solution to circumvent this issue in the case you need to have an object both available in kotlinx.serialization and as DynamicType in korte:

```kotlin
@Serializable
data class User(val key: String, val firstName: String, val lastName: String) : DynamicType<User> {
    companion object : DynamicType<User> by DynamicType({
        register(User::key)
        register(User::firstName)
        register(User::lastName)
    })
    override val DynamicTypeScope.__dynamicShape: DynamicShape<User> get() = User.run { DynamicTypeScope.__dynamicShape }
}
```
